AllCops:
  RunRailsCops: true

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 115

Style/Documentation:
  Enabled: false

Style/MultilineOperationIndentation:
    EnforcedStyle: indented

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/DotPosition:
  EnforcedStyle: trailing

Metrics/ParameterLists:
  Max: 6

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'uploads/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'config/initializers/rails_admin/**/*'
    #- 'spec/**/*'
