sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - 2.6.5
  - ruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
install: "bundle install --jobs 8"
script: "bundle exec rspec"
