sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
install: "bundle install --jobs 8"
script: "bundle exec rspec"
addons:
  code_climate:
    repo_token: 8501bc7f607cfd32d8a00e03fcbd111fbfe085bcf5171a70302d44898a72ff54
